Feature/#69_add_movie_endpoint
hal-cinema-2024/hal-cinema pull request #103
Opened 2024-06-08 06:15 UTC by sikigasa

## Issue
- #69

## 概要（対応内容・背景）
- Create_movie

## 動作確認したこと
-

## レビュー観点
-

## 備考

2024-06-08 08:03 UTC, murasame29 commented on backend/internal/adapter/controller/movie_post.go
> +	MovieID string `json:"movie_id"`
![image](https://github.com/hal-cinema-2024/hal-cinema/assets/77433104/638be8a6-f33c-4ea9-8b5e-bc99c5ed9d23)
jsonのkeyが違う

2024-06-08 08:05 UTC, murasame29 commented on backend/internal/adapter/controller/movie_post.go
> +		imageFiles, ok := form.File["thumbnail"]
これ、DBはthumbnail NotNullだけどErrorにならないの？

2024-06-08 08:33 UTC, murasame29 requested changes
いくつかコメント残したので修正してちょ

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/adapter/controller/movie_post.go
> +			log.Println("movieImage is not found")
log部分 "log"じゃなくて pkg配下のlog使って

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/adapter/controller/movie_post.go
> +			thumbnail = nil
これ、DBはthumbnail NotNullだけどErrorにならないの？

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/adapter/controller/movie_post.go
> +	MovieID string `json:"movie_id"`
![image](https://github.com/hal-cinema-2024/hal-cinema/assets/77433104/fc63c94d-8d73-4c2b-b368-8cf2717246e2)
jsonのkeyが違う

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/adapter/controller/movie_post.go
> +		for _, movieImageFile := range movieImageFiles {
これ何に使うの？

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/adapter/gateway/repository/movie.go
> +	for _, imagePath := range imagePaths {
これN＋１になってるくない？

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/adapter/gateway/repository/movie.go
> +func (r *MovieRepo) DeleteMovie(ctx context.Context, movieID string) (string, error) {
なんでstring返す必要があるの？

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/adapter/gateway/repository/movie.go
> +func (r *MovieRepo) UpdateMovie(ctx context.Context, movie *model.Movie) (string, error) {
これも何で空を返しているのにstringいるの？

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/router/v1/movie.go
> +	userRoute := v1.engine.Group("/movies")
これはuserRouteなんですか…？

2024-06-08 08:33 UTC, murasame29 commented on backend/internal/usecase/interactor/movie_post.go
> +	for _, image := range movie.MovieImage {
画像をいくつも(10とか)登録するときにボトルネックになりそう

2024-06-10 06:18 UTC, sikigasa commented on backend/internal/usecase/interactor/movie_post.go
> +	for _, image := range movie.MovieImage {
これでよさそう?

2024-06-10 06:30 UTC, murasame29 commented
Response Typeとかthumbnailの空部分治ってる？

2024-06-10 07:49 UTC, murasame29 requested changes

2024-06-10 08:02 UTC, murasame29 approved these changes
LGTM

2024-06-10 08:04 UTC, merged