add: swag
hal-cinema-2024/hal-cinema pull request #51
Opened 2024-05-18 15:56 UTC by sikigasa

## Issue
- #50

## 概要（対応内容・背景）
-

## 動作確認したこと
-

## レビュー観点
-

## 備考

2024-05-19 11:29 UTC, murasame29 commented on docs/apidocs.swagger.json
> +        "link": {
上映一覧とかだとLinkないけど必要そう？

2024-05-19 12:01 UTC, murasame29 requested changes
現存のスキーマ修正しつつ、他にも購入周りや、席予約周りのスキーマも追加して

2024-05-20 07:03 UTC, sikigasa commented on docs/apidocs.swagger.json
> +    "ApiServiceUpdateUserBody": {
なくなったらしい

2024-05-20 07:03 UTC, sikigasa commented on docs/apidocs.swagger.json
> +        "phoneNumber": {
ないなった

2024-05-20 08:30 UTC, sikigasa commented on docs/apidocs.swagger.json
> +    "v1Schedule": {
席の数と埋まってる数
termは分数入れれ内いかなっていう

2024-05-26 08:01 UTC, murasame29 approved these changes

2024-05-26 12:08 UTC, merged